#!/bin/sh
# This file is automatically added by husky
# Please do not edit this file directly.

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

if [ -z "$HUSKY" ]; then
  # This is to prevent the following error:
  # "Can't rewrite /some/path in /some/other/path on this platform"
  # See: https://github.com/typicode/husky/issues/556
  HUSKY=1
  export HUSKY

  # If this script is sourced, then the function below will be available
  # and we can call it to run the hook.
  # If this script is executed, then we need to run the hook directly.
  if [ "$0" = "$BASH_SOURCE" ]; then
    # This script is executed
    if command_exists run_with_husky; then
      run_with_husky "$@"
    else
      # This is a fallback for systems that don't have a working getent
      # (e.g. macOS without mdns responder)
      # We use the user's UID and GID to check if they are the owner
      # of the .husky directory
      user_id=$(id -u)
      group_id=$(id -g)
      husky_dir=$(cd "$(dirname "$0")/.." && pwd)
      
      if [ "$user_id" = "$(stat -c '%u' "$husky_dir")" ] && [ "$group_id" = "$(stat -c '%g' "$husky_dir")" ]; then
        # Run the hook directly
        "$@"
      else
        echo "husky: permission denied (are you trying to run hooks from a different user?)"
        exit 1
      fi
    fi
  fi
fi
